export const reducerCases = {
  SET_FILE_DATA: "SET_FILE_DATA",
  SET_CONTRACT: "SET_CONTRACT",
  SET_RETRIEVED_DATA: "SET_RETRIEVED_DATA",
  SET_REDIRECT: "SET_REDIRECT",
  SET_TRANSACTION_STATUS: "SET_TRANSACTION_STATUS",
};
